Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Style/Documentation:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/AlignHash:
  Severity: fatal
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/DotPosition:
  EnforcedStyle: leading

Style/DoubleNegation:
  Enabled: false

Style/SpaceAroundOperators:
  # When true, allows most uses of extra spacing if the intent is to align
  # with an operator on the previous or next line, not counting empty lines
  # or comment lines.
  AllowForAlignment: true

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - '*.gemspec'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'spec/**/*'
    - 'Gemfile'
    - 'app/views/**/*'
    - 'config/routes.rb'
