version: '3'

services:
  web:
    build:
      context: .
    env_file: ~/.ukpds/parliament.uk-prototype.env
    ports:
      - "3000:3000"
    links:
      - api

  api:
    build:
      context: ../member-service-api
    env_file: ~/.ukpds/member-service-api.env
